name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: copy
      env:
        SRC_FOLDER_PATH: 'dist'
        TARGET_BRANCH: 'dist'
      run: |
        files=$(find $SRC_FOLDER_PATH -type f)
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git fetch
        git checkout $TARGET_BRANCH
        git checkout ${GITHUB_REF##*/} -- $files
        git add -A
        git diff-index --quiet HEAD || git commit -am "Auto-update"
        git push origin $TARGET_BRANCH # push to remote branch
