name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: Publish demo to GitHub Pages
      uses: rayluo/github-pages-overwriter@v1.3

      with:
      
        source-directory: demo
        target-branch: gh-pages
    
    - name: Publish built files to dist branch
      uses: rayluo/github-pages-overwriter@v1.3

      with:
      
        source-directory: dist
        target-branch: dist
