name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: Publish demo to GitHub Pages
      uses: rayluo/github-pages-overwriter@v1.3

      with:
      
        source-directory: demo
        target-branch: gh-pages

    - name: Copy built files to dist branch
      env:
        SRC_FOLDER_PATH: 'dist'
        TARGET_BRANCH: 'dist'
      run: |
        git config user.name 'GitHub Action'
        git config user.email 'action@github.com'
        git branch -f $TARGET_BRANCH HEAD
        git checkout $TARGET_BRANCH --
        date > $SRC_FOLDER_PATH/date.txt
        ls $SRC_FOLDER_PATH
        git add --force $SRC_FOLDER_PATH
        git commit -m "Auto-update"
        git push -f origin `git subtree split -P $SRC_FOLDER_PATH`:refs/heads/$TARGET_BRANCH
